---
namespace: bellackn
name: homelab
version: 5.2.1
readme: README.md
authors:
  - Nico Bellack <hello@bellack.dev>
description: Holds various utils that are handy for a homelab infrastructure setup.
license:
  - MIT
tags:
  - infrastructure
  - lxc
  - proxmox
  - tools
  - mqtt
  - hms
repository: https://github.com/bellackn/ansible-collection-homelab
documentation: https://github.com/bellackn/ansible-collection-homelab
homepage: https://github.com/bellackn/ansible-collection-homelab
issues: https://github.com/bellackn/ansible-collection-homelab/issues
