---
namespace: bellackn
name: homelab
version: 5.0.0
readme: README.md
authors:
  - Nico Bellack <blcknc@pm.me>
description: Holds various utils that are handy for a homelab infrastructure setup.
license:
  - MIT
tags:
  - infrastructure
  - lxc
  - proxmox
  - tools
repository: https://github.com/bellackn/ansible-collection-homelab
documentation: https://github.com/bellackn/ansible-collection-homelab
homepage: https://github.com/bellackn/ansible-collection-homelab
issues: https://github.com/bellackn/ansible-collection-homelab/issues
