---
- name: Include variables
  ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yml"

- name: Install cri-dockerd
  ansible.builtin.include_tasks: cri-dockerd.yml

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ kubeadm_req_packages }}"
    state: present
  become: true

- name: Download Kubernetes GPG key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kubeadm_k8s_version }}/deb/Release.key"
    dest: /tmp/k8s-release.key
    mode: "0644"

- name: Import Kubernetes GPG key
  ansible.builtin.shell:
    cmd: set -o pipefail && cat /tmp/k8s-release.key | gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    executable: /bin/bash
  become: true
  changed_when: false

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubeadm_k8s_version }}/deb/ /"
    state: present

- name: Install Kubernetes tools
  ansible.builtin.apt:
    update_cache: true
    name:
      - kubelet
      - kubeadm
      - kubectl

- name: Prevent updates for Kubernetes tools
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Start kubelet
  ansible.builtin.systemd_service:
    name: kubelet
    state: started
    enabled: true
