---
- name: "Create LXC {{ item.hostname }}"
  community.general.proxmox:
    proxmox_default_behavior: no_defaults
    api_user: "{{ proxmox_lxc_api_user }}"
    api_password: "{{ proxmox_lxc_api_password }}"
    api_host: "{{ proxmox_lxc_proxmox_host }}"
    node: "{{ proxmox_lxc_proxmox_node }}"
    hostname: "{{ item.hostname }}"
    password: "{{ item.password }}"
    state: present
    force: "{{ item.force | default('no') }}"
    pubkey: "{{ item.pubkey }}"
    validate_certs: no
    ostemplate: "{{ item.ostemplate }}"
    netif: "{{ item.netif }}"
    cpus: "{{ item.cpus | default(proxmox_lxc_cpus) }}"
    cores: "{{ item.cores | default(proxmox_lxc_cores) }}"
    cpuunits: "{{ item.cpuunits | default(proxmox_lxc_cpuunits) }}"
    storage: "{{ item.storage | default(proxmox_lxc_storage) }}"
    disk: "{{ item.disk | default(proxmox_lxc_disk) }}"
    memory: "{{ item.memory | default(proxmox_lxc_memory) }}"
    onboot: "{{ item.onboot | default('yes') }}"
    swap: "{{ item.swap | default(proxmox_lxc_swap) }}"
    vmid: "{{ item.vmid | default(omit) }}"
    unprivileged: "{{ item.unprivileged | default('yes') }}"
    features: "{{ item.features | default(proxmox_lxc_features) }}"
  delegate_to: localhost
  register: proxmox_lxc_created

- name: "Wait for {{ item.hostname }} creation"  # noqa 503
  delegate_to: localhost
  wait_for:
    timeout: "{{ proxmox_lxc_creation_timeout }}"
  when: proxmox_lxc_created.changed

- name: "Start {{ item.hostname }}"
  community.general.proxmox:
    proxmox_default_behavior: no_defaults
    api_user: "{{ proxmox_lxc_api_user }}"
    api_password: "{{ proxmox_lxc_api_password }}"
    api_host: "{{ proxmox_lxc_proxmox_host }}"
    node: "{{ proxmox_lxc_proxmox_node }}"
    hostname: "{{ item.hostname }}"
    state: started
  delegate_to: localhost
  register: proxmox_lxc_started

- name: "Wait for {{ item.hostname }} to be started"  # noqa 503
  wait_for:
    timeout: 5
  delegate_to: localhost
  when: proxmox_lxc_started.changed

- name: Ping outside  # noqa 503
  command: "lxc-attach -n {{ proxmox_lxc_started.msg[3:6] }} -- ping {{ proxmox_lxc_ping_server }} -c 2"
  delegate_to: "{{ proxmox_lxc_proxmox_node }}"
  when: proxmox_lxc_created.changed

- name: "Wait for {{ item.hostname }} network"
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    search_regex: OpenSSH
    timeout: "{{ proxmox_lxc_network_timeout }}"
  delegate_to: localhost
