---
- name: "Stop LXC {{ item.hostname }}"
  community.general.proxmox:
    proxmox_default_behavior: no_defaults
    api_user: "{{ px_lxc_api_user }}"
    api_password: "{{ px_lxc_api_password }}"
    api_host: "{{ px_lxc_proxmox_host }}"
    node: "{{ px_lxc_proxmox_node }}"
    hostname: "{{ item.hostname }}"
    vmid: "{{ item.vmid | default(omit) }}"
    state: stopped
  delegate_to: localhost
  register: lxc_stop
  ignore_errors: yes

- name: "Delete LXC {{ item.hostname }}"
  community.general.proxmox:
    proxmox_default_behavior: no_defaults
    api_user: "{{ px_lxc_api_user }}"
    api_password: "{{ px_lxc_api_password }}"
    api_host: "{{ px_lxc_proxmox_host }}"
    node: "{{ px_lxc_proxmox_node }}"
    hostname: "{{ item.hostname }}"
    vmid: "{{ item.vmid | default(omit) }}"
    state: absent
  delegate_to: localhost
  when: "'Hostname doesn\\'t exist' not in lxc_stop.msg"
