---
- name: Install proxmoxer
  pip:
    name: proxmoxer
    state: present
  delegate_to: localhost

- name: Create LXC containers
  include_tasks: create_lxc.yml
  loop: "{{ px_lxc_containers_present }}"

- name: Delete LXC containers
  include_tasks: delete_lxc.yml
  loop: "{{ px_lxc_containers_absent }}"
