---
- name: "Stop LXC '{{ item.hostname }}'"
  community.general.proxmox:
    api_host: "{{ item.api_host | default(proxmox_lxc_api_host) }}"
    api_password: "{{ item.api_password | default(proxmox_lxc_api_password) }}"
    api_user: "{{ item.api_user | default(proxmox_lxc_api_user) }}"
    hostname: "{{ item.hostname }}"
    node: "{{ item.node | default(proxmox_lxc_node) }}"
    state: stopped
  register: lxc_stop
  ignore_errors: true

- name: "Delete LXC '{{ item.hostname }}'"
  community.general.proxmox:
    api_host: "{{ item.api_host | default(proxmox_lxc_api_host) }}"
    api_password: "{{ item.api_password | default(proxmox_lxc_api_password) }}"
    api_user: "{{ item.api_user | default(proxmox_lxc_api_user) }}"
    hostname: "{{ item.hostname }}"
    node: "{{ item.node | default(proxmox_lxc_node) }}"
    state: absent
  when:
    - "'Hostname doesn\\'t exist' not in lxc_stop.msg"
    - "'No VM with name' not in lxc_stop.msg"
