---
galaxy_info:
  role_name: hass_control
  namespace: bellackn
  author: Nico Bellack
  description: Set and retrieve Home Assistant configuration files
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - homeassistant
