---
name: CI

"on":
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  test-role-proxmox-lxc:
    name: Test proxmox_lxc role
    uses: ./.github/workflows/test_role.yml
    with:
      ROLE_NAME: proxmox_lxc

  test-role-hms-mqtt-publisher:
    name: Test hms_mqtt_publisher role
    uses: ./.github/workflows/test_role.yml
    with:
      ROLE_NAME: hms_mqtt_publisher
  
  test-role-kubeadm:
    name: Test kubeadm role
    uses: ./.github/workflows/test_role.yml
    with:
      ROLE_NAME: kubeadm

  ansible-test:
    name: Run ansible-test
    runs-on: ubuntu-latest
    steps:
      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          testing-type: sanity

  galaxy:
    name: Build collection
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Build collection tarball
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          publish: false
