---
name: Release

"on":
  release:
    types:
      - published

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a new import on Ansible Galaxy
        uses: robertdebock/galaxy-action@affc5472cd0b08f64a51eafba49b08898c1bbeb8
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
